package sqlid

import (
	"encoding/json"
	"os"
	"testing"
)

// parityRow mirrors one record in testdata/parity.json, generated by the
// reference Python implementation in py/. The Go results must match it exactly.
type parityRow struct {
	Input      Statement `json:"input"`
	Normalized Statement `json:"normalized"`
	Id         Id        `json:"id"`
	Hash       Hash      `json:"hash"`
	RawId      Id        `json:"raw_id"`
	RawHash    Hash      `json:"raw_hash"`
}

func loadParity(t *testing.T) []parityRow {
	t.Helper()
	data, err := os.ReadFile("testdata/parity.json")
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var rows []parityRow
	if err := json.Unmarshal(data, &rows); err != nil {
		t.Fatalf("decode golden: %v", err)
	}
	return rows
}

// TestParityWithPython asserts the Go implementation reproduces the Python
// reference normalization, SQL IDs and SQL hashes for every corpus statement.
func TestParityWithPython(t *testing.T) {
	for _, row := range loadParity(t) {
		t.Run(string(row.Input), func(t *testing.T) {
			if got := Normalize(row.Input); got != row.Normalized {
				t.Errorf("Normalize = %q, want %q", got, row.Normalized)
			}
			if got := SQLId(row.Input); got != row.Id {
				t.Errorf("SQLId = %q, want %q", got, row.Id)
			}
			if got := SQLHash(row.Input); got != row.Hash {
				t.Errorf("SQLHash = %d, want %d", got, row.Hash)
			}
			if got := SQLIdRaw(row.Input); got != row.RawId {
				t.Errorf("SQLIdRaw = %q, want %q", got, row.RawId)
			}
			if got := SQLHashRaw(row.Input); got != row.RawHash {
				t.Errorf("SQLHashRaw = %d, want %d", got, row.RawHash)
			}
		})
	}
}
