package sqlid

import (
	"encoding/json"
	"os"
	"testing"
)

// parityRow mirrors one record in testdata/parity.json, generated by the
// reference Python implementation in py/. The Go results must match it exactly.
type parityRow struct {
	Input      Statement `json:"input"`
	Normalized Statement `json:"normalized"`
	ID         ID        `json:"id"`
	RawID      ID        `json:"raw_id"`
	Hash       Hash      `json:"hash"`
	RawHash    Hash      `json:"raw_hash"`
}

func loadParity(t *testing.T) []parityRow {
	t.Helper()
	data, err := os.ReadFile("testdata/parity.json")
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var rows []parityRow
	if err := json.Unmarshal(data, &rows); err != nil {
		t.Fatalf("decode golden: %v", err)
	}
	return rows
}

// TestParityWithPython asserts the Go implementation reproduces the Python
// reference normalization, SQL IDs and SQL hashes for every corpus statement.
func TestParityWithPython(t *testing.T) {
	for _, row := range loadParity(t) {
		t.Run(string(row.Input), func(t *testing.T) {
			if got := Normalize(row.Input); got != row.Normalized {
				t.Errorf("Normalize = %q, want %q", got, row.Normalized)
			}
			if got := SQLID(row.Input); got != row.ID {
				t.Errorf("SQLID = %q, want %q", got, row.ID)
			}
			if got := SQLHash(row.Input); got != row.Hash {
				t.Errorf("SQLHash = %d, want %d", got, row.Hash)
			}
			if got := SQLRawID(row.Input); got != row.RawID {
				t.Errorf("SQLRawID = %q, want %q", got, row.RawID)
			}
			if got := SQLRawHash(row.Input); got != row.RawHash {
				t.Errorf("SQLRawHash = %d, want %d", got, row.RawHash)
			}
		})
	}
}
