package sqlid

import (
	"encoding/json"
	"os"
	"testing"
)

// The raw contract values predate normalization and must never change.
func TestSQLRawIDContract(t *testing.T) {
	cases := map[Statement]ID{
		"select 1":            "y30pf6xwqt3x",
		"select * from table": "9nq4tw9gnts86",
	}
	for stmt, want := range cases {
		if got := SQLRawID(stmt); got != want {
			t.Errorf("SQLRawID(%q) = %q, want %q", stmt, got, want)
		}
	}
}

func TestSQLRawHashContract(t *testing.T) {
	if got := SQLRawHash("select 1"); got != Hash(3150668925) {
		t.Errorf("SQLRawHash(select 1) = %d, want 3150668925", got)
	}
}

func TestSQLIDAndHashNormalize(t *testing.T) {
	if got := SQLID("select 1"); got != ID("dmrrk1sbj01z") {
		t.Errorf("SQLID(select 1) = %q, want dmrrk1sbj01z", got)
	}
	if got := SQLHash("select 1"); got != Hash(1891139647) {
		t.Errorf("SQLHash(select 1) = %d, want 1891139647", got)
	}
	// Equivalent statements collapse to the same ID.
	if SQLID("SELECT   1") != SQLID("select 1") {
		t.Error("normalized SQLID differs for equivalent statements")
	}
}

func TestBase32OfZero(t *testing.T) {
	if got := digest(0).base32(); got != ID(alphabet[:1]) {
		t.Errorf("digest(0).base32() = %q, want %q", got, alphabet[:1])
	}
}

func TestBase32Carry(t *testing.T) {
	if got := digest(radix).base32(); got != ID("10") {
		t.Errorf("digest(32).base32() = %q, want 10", got)
	}
}

// parityRow mirrors one record in testdata/parity.json, generated by the
// reference Python implementation in py/. The Go results must match it exactly.
type parityRow struct {
	Input      Statement `json:"input"`
	Normalized Statement `json:"normalized"`
	ID         ID        `json:"id"`
	RawID      ID        `json:"raw_id"`
	Hash       Hash      `json:"hash"`
	RawHash    Hash      `json:"raw_hash"`
}

func loadParity(t *testing.T) []parityRow {
	t.Helper()
	data, err := os.ReadFile("testdata/parity.json")
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var rows []parityRow
	if err := json.Unmarshal(data, &rows); err != nil {
		t.Fatalf("decode golden: %v", err)
	}
	return rows
}

// TestParityWithPython asserts the Go implementation reproduces the Python
// reference normalization, SQL IDs and SQL hashes for every corpus statement.
func TestParityWithPython(t *testing.T) {
	for _, row := range loadParity(t) {
		t.Run(string(row.Input), func(t *testing.T) {
			if got := Normalize(row.Input); got != row.Normalized {
				t.Errorf("Normalize = %q, want %q", got, row.Normalized)
			}
			if got := SQLID(row.Input); got != row.ID {
				t.Errorf("SQLID = %q, want %q", got, row.ID)
			}
			if got := SQLHash(row.Input); got != row.Hash {
				t.Errorf("SQLHash = %d, want %d", got, row.Hash)
			}
			if got := SQLRawID(row.Input); got != row.RawID {
				t.Errorf("SQLRawID = %q, want %q", got, row.RawID)
			}
			if got := SQLRawHash(row.Input); got != row.RawHash {
				t.Errorf("SQLRawHash = %d, want %d", got, row.RawHash)
			}
		})
	}
}
